---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-cloud-data
  namespace: uptime-kuma-cloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
